export const COMMON_NAV_RESET = 'COMMON_NAV_RESET';
export const COMMON_ROUTE_RESET = 'COMMON_ROUTE_RESET';
export const COMMON_BREADCRUMB_RESET = 'COMMON_BREADCRUMB_RESET';
export const COMMON_ROUTE_PUSH = 'COMMON_ROUTE_PUSH';
